### ISSUE TITLE
ctre::range match result not constexpr

### ISSUE THREAD

**Issue by PengyiPan** [hanickadot/compile-time-regular-expressions#144]
Hello!
I'm tying to extract the format specifier from a printf-like format string. I'm able to use ctre::range to get all tags. For example:

```c++
    using namespace std::string_view_literals;
    constexpr auto pattern = ctll::fixed_string{"%{1}(s|d)"};
    constexpr auto target = "CTRE is %s better than %d other libs!"sv;

    for (auto match: ctre::range<pattern>(target)) {
        std::cout << "Tag is=" << match.get<1>().to_view() << std::endl;
    }
```
will output
```console
Tag is=s
Tag is=d
```

But I really want to treat these 2 matches differently (at compile time of course) and print different messages. For example:
```c++
    for (auto match: ctre::range<pattern>(target)) {
        if constexpr (match.get<1>().to_view() == "d"sv) {
            std::cout << "Tag is A NUMBER=" << match.get<1>().to_view() << std::endl;
        }
        if constexpr (match.get<1>().to_view() == "s"sv) {
            std::cout << "Tag is A STR=" << match.get<1>().to_view() << std::endl;
        }
    }
```
And it won't compile. Complaining about '_match_' in the for loop not being constexpr.

Is there way to fix/get around this? Thanks!

FYI, I'm using the latest commit d0f3778 from 2020-11-12. G++ 10.2.0

**Comment by hanickadot** [comment]
You can't do this because `match` variable is not constexpr and generally cycles like `for` are not constexpr. One way how to do it is calculate number of pieces by a helper function and store the result into a constexpr variable, use that variable to allocate `std::array` or N items of type `decltype(*iterator)` and then with `std::index_sequence` and fold expression iterate over each value.

**Comment by PengyiPan** [comment]
Will give it a try. Thank you!
