### ISSUE TITLE
Feature Request : regex replace

### ISSUE THREAD

**Issue by beemibrahim** [hanickadot/compile-time-regular-expressions#250]
The C++ Standard Library has a match and a replace function , and this 
ctre library has a match function but not a replace function

**Comment by hanickadot** [comment]
It's not my intention to provide such functionality. Because I generally want to support any range and replacing is string specific operation, probably it could be done lazily with an output range, but that would be really complex thing to do.

There is a code how to do it naively with `std::ostringstream`:
https://compiler-explorer.com/z/coE498P68

**Comment by beemibrahim** [comment]
Does it have the same speed as searching , since searching is 10x faster then std::regex_search() , is replacing 10x faster then std::regex_replace()

**Comment by hanickadot** [comment]
It depends on the pattern but it should be generally faster than std::regex_replace

**Comment by kelbon** [comment]
But its really usefull thing and it is so untrivial to do without library support(and even more hard in effective way)
And std::regex_replace supports special syntax for output format, for example:
https://godbolt.org/z/EGEnh5W7z
You can accept output iterator for CharType and bidirectional range, if you do not want support just strings

**Comment by Robotechnic** [comment]
Hello,
I tried to do the same but in c++17 and I get an error:

```
missing 'template' keyword prior to dependent template name 'get'
```

This is just a test to try achieving replace with capture groups support, I will create a better version once I figure out how to fix this version. Here it assume that the regex match the entire string.

```cpp
template<CTRE_REGEX_INPUT_TYPE input, typename... Modifiers>
std::optional<std::string> replace(const std::string_view &str, const std::string_view &replacement) {
    auto match = ctre::match<input, Modifiers...>(str);
    if (!match) {
		return std::nullopt;
	}
	std::stringstream result;
	const size_t size = match.size();
	for (int i = 0; i < str.size() - 1; i++) {
		if (str.at(i) == '$' && str.at(i + 1) >= '0' && str.at(i + 1) <= '9') {
			const int index = str.at(i + 1) - '0';
			if (index < size) {
                result << match.get<index>().to_view();
			}
			i++;
		} else {
			result << str.at(i);
		}
	}
	return result.str();
}
```
Here, I know it is because the match require to know the type of the regex in it template but I struggle to figure out how to pass it correctly.
