### ISSUE TITLE
Is ctre faster then perl regex ??

### ISSUE THREAD

**Issue by beemibrahim** [hanickadot/compile-time-regular-expressions#256]
I want to convert a perl program to C++ , and since perl is made in C , I've decided to get a C regex library. I found one called pcre made in C , and they said it was very fast. Since perl regex also uses C , should pcre be as fast as perl regex. I don't know , and since my code is full of ctre stuff and still so slow ( I don't know why ) , I've decided to use primitive C. 

So the question comes down to :

Is ctre faster then perl regex ???

Also you should open a discussions channel , because I am having to post an issue for this even though its a question

**Comment by hanickadot** [comment]
the question you are asking is same as asking which programming language is faster. Only thing CTRE is doing is converting a regex into assembly (with help of compiler), and if your regex is slow, there can be issue in its design, especially around greedy/lazy cycles instead of possessive ones. PCRE library is generally really fast, same as CTRE. In case of CTRE it depends on your compiler and optimisation levels.

I don't want to open a discussion channel as I'm doing this only in my free time. Feel free to start such discussion at [includecpp.org](https://www.includecpp.org)'s discord where I'm sometimes available.
