### ISSUE TITLE
Comprehensive list of required changes to make the lib C++14 compatible

### ISSUE THREAD

**Issue by Manu343726** [hanickadot/compile-time-regular-expressions#33]
Hi,

I think we talked about this some weeks ago on twitter, but I would love if you could share the conflictive points you're aware of. I want to decide whether to bump my projects to C++17 or keep C++14 support, and I need your library to write a command line arg parser. I'm not sure whether updating all my toolchains or accepting the challenge of porting CTRE to C++14 will be more challenging.

**Comment by hanickadot** [comment]
I tried to port it to C++14 in a branch "c++14" :) 

hard problem:
- `auto &` template arguments and references as a template argument, it will lead to code like:
```
regex_match<decltype(re), re>(subject);
```

soft problems:
- folded expression - you need it only for trampolining, otherwise it's only recursion and you are limited in length of your pattern

You can continue, it's not much, but I'm afraid of supporting C++14/17/20 versions together would be hard. And I don't have time to do that now. I can try in spare time between Christmas and New Year's Eve.
